### ISSUE TITLE
warning generated on install

### ISSUE THREAD

**Issue by jsve** [spuun/node-jontelldus#1]
getting this warning when npm installing:

CXX(target) Release/obj.target/jontelldus/src/AddDeviceWorker.o
In file included from ../src/AddDeviceWorker.cc:1:
../src/AddDeviceWorker.h:15:9: warning: private field 'deviceId' is not used [-Wunused-private-field]
    int deviceId;
        ^
1 warning generated.

Not sure if related, but fails on require:

> var jtelldus = require('jontelldus');
[1]    64876 abort      node

Running on node v7.0.0

**Comment by spuun** [comment]
Thanks for feedback!

That warning is no problem as long as you dont get any errors during compile time. I'll remove that variable to remove the warning though.

I'll try to find some time to try it with v7.0.0. I'm running it on a rpi with v6.2.2 without any problem at the moment.

**Comment by jsve** [comment]
Getting same abort on node v6.2.2 and node v6.10.0

I'm running this on mac OS. could this be the reason?

**Comment by jsve** [comment]
tried it on the raspberry now. seems to work (node 6.9.5). Any quick fixes to make it work on mac os?

**Comment by spuun** [comment]
It must be something with the linking to telldus-core, i guess.

This is my first and only (so far) addon for node, and i havn't done anything for a while, so i'm a little bit rusty. I need to set up a dev env, which will be on a macbook so it will be tested on macos this time :)

**Comment by spuun** [comment]
So just published a new version to npm. To be honest, its not very tested, but i dont get the trap error anymore!

**Comment by jsve** [comment]
Seems to start on the mac as well now. Progress :)
